## Project Euler problem 2: Even Fibonacci numbers
## Each term in the fibonacci sequence is generated by adding the two previous terms.
## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def FibonacciSequenceGetEvenTermsSum(maxValue):
    x = 1
    y = 1
    z = 0
    res = 0

    while z < maxValue:
        z = (x + y)
        if z%2 == 0:
            res = res + z

        x = y
        y = z

    return res

def main():
    print(">> Problem 2 started :")
    res = FibonacciSequenceGetEvenTermsSum(4000000)
    print("Res is : ", res)

if __name__ == "__main__":
    main()